### ISSUE TITLE
How to uninstall useless packages of virtual environment?

### ISSUE THREAD

**Issue by luoxh8** [invl/pip-autoremove#31]
I tried to use the pip-autoremove package in my virtual environment, but the package he searched for was only the system environment, not my virtual environment. I did not see related issues elsewhere. I will thank you if you can answer my question.   :)

![image](https://user-images.githubusercontent.com/30749019/86996658-c4fc7000-c1de-11ea-89d1-b9aea3003f52.png)

**Comment by tresni** [comment]
See #22  and [my branch](https://github.com/tresni/pip-autoremove) which includes a fix for this (uses whichever pip the python interpreter knows about so works fine in venv)

**Comment by tresni** [comment]
Should be addressed by the merge of #42 and the new release, please close if that resolves your issue.

**Comment by luoxh8** [comment]
Thank you for your reply. Problem solved.
